num_workers: 10
batch_size: 1
cuda: 0
weight_name: "map" # Used during resume, select with model to load from [miou, macc, acc, miou_ch..., latest]
enable_cudnn: True
checkpoint_dir: "/home/user/zhanwenxiao/instancesegmentation/code/instance_changedetection/outputs/hkcd-best"
model_name: SiamEncFusionSkipKPConv # SiameseKPConvUnshared SiameseKPConv
precompute_multi_scale: False # Compute multiscate features on cpu for faster training / inference
enable_dropout: False
voting_runs: 1

tracker_options: # Extra options for the tracker
  full_pc: True
  full_res: True
  save_pc: True
  name_test: ""

hydra:
  run:
    dir: ${checkpoint_dir}/eval/${now:%Y-%m-%d_%H-%M-%S}
