# Those arguments defines the training hyper-parameters
training:
    epochs: 550
    num_workers: 5 #10
    batch_size: 5 #10
    shuffle: True
    cuda: 1 # -1 -> no cuda otherwise takes the specified index
    precompute_multi_scale: False # Compute multiscate features on cpu for faster training / inference
    optim:
        base_lr: 0.0001 # 0.0001 # 0.01
        grad_clip: 100
        optimizer:
            class: Adam #SGD #Adam
            params:
#                momentum: 0.98
                lr: ${training.optim.base_lr} # The path is cut from training
                weight_decay: 1e-3
        lr_scheduler: ${lr_scheduler}
        bn_scheduler:
            bn_policy: "step_decay"
            params:
                bn_momentum: 0.02
                bn_decay: 0.9
                decay_step : 1000
                bn_clip : 1e-2
        early_stop: -1 #50 # Set to -1 if no early stopping wanted else indicate the number of step with augmentation of miou_ch on val ds
    weight_name: "latest" # Used during resume, select with model to load from [miou, macc, acc..., latest]
    enable_cudnn: True
    checkpoint_dir: "/home/user/zhanwenxiao/instancesegmentation/code/instance_changedetection/outputs/SiamKPConv-2025-08-08/SiamKPConv-2025-08-08-SiamEncFusionSkipKPConv-20250808_154244" #"/home/user/zhanwenxiao/instancesegmentation/code/instance_changedetection/outputs/SiamKPConv-2025-08-04/SiamKPConv-2025-08-04-SiamEncFusionSkipKPConv-20250804_112742" #"/home/user/zhanwenxiao/instancesegmentation/code/instance_changedetection/outputs/SiamKPConv-2025-01-21/SiamKPConv-2025-01-21-SiamEncFusionSkipKPConv-20250121_101657" #"/home/user/zhanwenxiao/instancesegmentation/code/instance_changedetection/outputs/SiamKPConv-2025-01-16/SiamKPConv-2025-01-16-SiamEncFusionSkipKPConv-20250116_184247"
# Those arguments within experiment defines which model, dataset and task to be created for benchmarking
# parameters for Weights and Biases
wandb:
    entity: ""
    project: "Change_detection"
    log: False
    notes: "HKCD "
    name: "HKCD SiameseKPConv"
    public: True # It will be display the model within wandb log, else not.
    config:
        model_name: ${model_name}


# parameters for TensorBoard Visualization
tensorboard:
    log: False
